version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    - node/with-cache:
      steps:
        - run: npm run build
  build-and-push-docker-image:
    machine: true
    steps:
      - run: echo "built docker image"
      - run: echo "pushed docker image to registry"
workflows:
  version: 2.1
  hw-ci-cd:
    jobs:
      - install-and-test
      - build:
        requires:
          - install-and-test
        filters:
            branches:
              only: master
      - build-and-push-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master
