version: 2.1
orbs:
  node: circleci/node@2.0.1
  docker: circleci/docker@1.0.1
jobs:
  install-test-build:
      executor:
        name: node/default
      steps:
        - checkout
        - run: npm install
        - run: npm test
        - run: npm run build
  install-test-build-cache:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
      - save_cache:
          key: built-app-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
            - Dockerfile
  build-docker-image-only:
    executor:
      name: docker/docker
    steps:
      - restore_cache:
          keys: built-app
      - setup_remote_docker
      - run: docker build . -t my-first-image
  build-docker-image-with-orb:
      steps:
        - docker/publish:
          cache_from: '$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest'
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          deploy: false
  # build-and-push-docker-image:
  #   executor: docker/docker
  #   steps:
  #     # - node/test
  #     - checkout
  #     - run: npm install
  #     - run: npm test
  #     - run: npm run build
  #     - setup_remote_docker
  #     - docker/check
  #     - docker/build:
  #         image: my_repo/orb-test
      # - docker/push:
      #     digest-path: /tmp/digest.txt
      #     image: my_repo/orb-test
      # - run:
      #     command: |
      #       echo "Digest is: $(</tmp/digest.txt)"
workflows:
  version: 2
  hw-ci-cd:
    jobs:
      - install-test-build-cache
      - build-docker-image-with-orb:
         requires:
           - install-test-build-cache
      # - node/test:
      #   filters:
      #     branches:
      #       ignore: master
      # - build-and-push-docker-image:
      #   filters:
      #     branches:
      #       only: master