version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  install-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  hw-ci:
    jobs:
      - install-test