version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-docker-image:
    machine: true
    steps:
      - run: echo "built docker image"
  push-docker-image:
    machine: true
    steps:
      - run: echo "pushed docker image to registry"
workflows:
  version: 2
  hw-ci-cd:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - push-docker-image:
          requires:
            - build-docker-image
          filters:
            branches:
              only: master
