version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    executor:
      name: node/default
    steps:
      - run: npm test
  build-docker-image:
    machine: true
    steps:
      - run: echo "built docker image"
  push-docker-image:
    machine: true
    steps:
      - run: echo "pushed docker image to registry"
workflows:
  version: 2
  hw-ci:
    triggers:
      - schedule:
        filters:
          branches:
            ignore:
              - master
    jobs:
      - build
      - test:
          requires:
            - build
  hw-cd:
    triggers:
      - schedule:
        filters:
          branches:
            only:
              - master
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test
      - push-docker-image:
          requires:
            - build-docker-image
