version: 2.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    steps:
      - run: npm test
  build-docker-image:
    steps:
      - run: echo "built docker image"
  push-docker-image:
    steps:
      - run: echo "pushed docker image to registry"
workflows:
    version: 2
  hw-ci:
    jobs:
      - build
      - test:
          requires:
            - build
  hw-cd:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          triggers:
            filters:
              branches:
                only:
                  = master
          requires:
            - test
      - push-docker-image:
          requires:
            - build-docker-image
