version: 2.1
orbs:
  node: circleci/node@2.0.1
  # docker: circleci/docker@1.0.1
jobs:
  # build:
  #   - node/with-cache:
  #     steps:
  #       - run: npm run build
  build-and-push-docker-image:
    machine: true
    steps:
      - run: echo "built docker image"
      - run: echo "pushed docker image to registry"
workflows:
  version: 2
  hw-ci-cd:
    jobs:
      - node/test
      # - build:
      #     requires:
      #       - node/test
      #     filters:
      #       branches:
      #         only: master
      - build-and-push-docker-image:
          requires:
            - node/test
          filters:
            branches:
              only: master
